version: '3'
services:
  app:
    image: dev.michaelkimball/gm-tools:latest
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: 'mongo'
    container_name: 'gm-tools-mongo'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'